apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/mtv-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: release-v2.8
    target:
      kind: Subscription
