---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../groups/all

helmCharts:
  - name: argocd-app-of-app
    valuesFile: values.yaml
    namespace: openshift-gitops

patches: []
