apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-manage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: minio-manage
  namespace: {{ .Release.Namespace }} 