kind: TempoStack
apiVersion: tempo.grafana.com/v1alpha1
metadata:
  name: otel-tempo
  namespace: openshift-tempo-operator
spec:
  resources:
    total:
      limits:
        cpu: "2"
        memory: 2Gi
  storage:
    secret:
      name: tempo-s3
      type: s3
  storageSize: 1Gi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
