---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-nmstate-console-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-nmstate-console-plugin
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - label
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-nmstate-console-plugin
subjects:
  - kind: ServiceAccount
    name: job-nmstate-console-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-nmstate-console-plugin
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-nmstate-console-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          env:
            - name: PLUGIN_NAME
              value: nmstate-console-plugin
          command:
            - /bin/bash
            - -c
            - /scripts/console-plugin-job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: job-nmstate-console-plugin
            defaultMode: 0755
      restartPolicy: Never
      serviceAccount: job-nmstate-console-plugin
      serviceAccountName: job-nmstate-console-plugin
  backoffLimit: 4
