apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/serverless-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: stable
    target:
      kind: Subscription
