---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - ./subscription.yaml
  - ./console-plugin-job.yaml
  - ./console-plugin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-tekton-console-plugin
    files:
      - console-plugin-job.sh
