apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: node-remediation-console-plugin
spec:
  backend:
    service:
      basePath: /
      name: node-healthcheck-node-remediation-console-plugin
      namespace: openshift-workload-availability
      port: 9443
    type: Service
  displayName: Node Remediation
  i18n:
    loadType: ""
