---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-logging-view-plugin
    files:
      - console-plugin-job.sh
