apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "openshift-logging"

resources:
  - ../../../../components/minio-job/

secretGenerator:
  - name: minio-user-info
    type: Opaque
    literals:
      - BUCKET=loki
      - USER=loki
      - PASSWORD=openshift4!