apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-mtv

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - console-plugin-job.yaml
  - console-plugin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-forklift-console-plugin
    files:
      - console-plugin-job.sh
