apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/gpu-operator-certified/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: v24.6
    target:
      kind: Subscription
