apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/cluster-observability-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'development'
    target:
      group: operators.coreos.com
      kind: Subscription
      name: cluster-observability-operator
      namespace: openshift-operators
