apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/virtualization-configuration/

patches:
  - patch: |-
      - op: replace
        path: /spec/featureGates/enableCommonBootImageImport
        value: false
    target:
      kind: HyperConverged
